spring:
  mail:
    host: "smtp.gmail.com"
    port: 587
    username: "your mail"
    password: "your pass"
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enabled: true
      mail.smtp.starttls.required: true
  application:
    name: esn-web-backend
  config:
    import: classpath:endpoint.yaml
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/esn
    username: root
    password: root
  mvc:
    async:
      request-timeout: 10s


  servlet:
    multipart:
      max-file-size: 10MB
  codec:
    max-in-memory-size: 10MB
  profiles:
    active: dev

server:
  port: 6969


logging:
  level:
    org.zalando.logbook: trace


logbook:
  format:
    style: http

stripe.secret.key:

openexchangerates.api.key: "your_key"